openapi: 3.0.1
info:
  title: Connect
  description:
    This is a printer connect webservice. It is compatible with another 3D printer services, so many applications
    which use this service
  contact:
    email: developer@prusa3d.cz
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about API
  url: http://connect.prusa3d.cz
tags:
  - name: octoprint
    description: Octoprint compatible
paths:
  /api/connection:
    get:
      tags:
        - octoprint
      summary: Retrieve a mock for current connection settings.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    $ref: "#/components/schemas/OctoConnCurrent"
                  options:
                    $ref: "#/components/schemas/OctoConnOptions"
        403:
          $ref: "#/components/responses/Unauthorized"
    post:
      tags:
        - octoprint
      summary: Mock for issue a connection command. Do not do anything.
      security:
        - ApiKeyAuth: []
      responses:
        204:
          description: No Content
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/timelapse:
    get:
      tags:
        - octoprint
      security:
        - ApiKeyAuth: []
      summary: Retrieves a moked list of timelapses and the current config.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type: object
                    properties:
                      type:
                        type: string
                  enabled:
                    type: boolean
                    example: false
                  files:
                    type: array
                    items:
                      type: string
                      nullable: true
                example:
                  config:
                    type: off
                  enabled: false
                  files: []
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/printerprofiles:
    get:
      tags:
        - octoprint
      summary: Retrive a mock of octoprinter printer profile
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  profiles:
                    $ref: "#/components/schemas/OctoProfiles"
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/printer:
    get:
      tags:
        - octoprint
      summary: Retrive the current printer state
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: exclude
          description: A list of attributes to not return in the response.
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature:
                    $ref: "#/components/schemas/OctoTemperatureState"
                  sd:
                    $ref: "#/components/schemas/OctoSDState"
                  state:
                    $ref: "#/components/schemas/OctoPrinterState"
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/printer/sd:
    get:
      tags:
        - octoprint
      summary: Retrieves the current state of the printer’s SD card.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/OctoSDState"
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/job:
    get:
      tags:
        - octoprint
      summary: Retrieve information about the current job (if there is one).
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  job:
                    $ref: "#/components/schemas/OctoJob"
                  progress:
                    $ref: "#/components/schemas/OctoProgress"
                  state:
                    enum:
                      [
                        "Operational",
                        "Printing",
                        "Pausing",
                        "Paused",
                        "Cancelling",
                        "Error",
                        "Offline",
                      ]
        403:
          $ref: "#/components/responses/Unauthorized"
        409:
          description: File not found or wrong format.
    post:
      tags:
        - octoprint
      summary: Issue a job command.
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  enum: ["start", "restart", "pause", "cancel"]
                  example: start
      responses:
        204:
          description: No error
        403:
          $ref: "#/components/responses/Unauthorized"
        409:
          description: If not is project, file not found or printer is printing.
        501:
          description: Unsupported command.
  /api/system/commands:
    get:
      tags:
        - octoprint
      summary: Retrieves all configured system commands. Currently just a mock.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OctoCommands"
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/users:
    get:
      tags:
        - octoprint
      summary: Retrieves a list of all registered users in OctoPrint. Currently just a mock.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/OctoUsers"
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/downloads/{target}/{filename}:
    parameters:
      - in: path
        name: target
        required: true
        description: The target location to which to download the file (local, sdcard).
        schema:
          type: string
          default: local
          enum:
            - local
            - sdcard
      - in: path
        name: filename
        required: true
        description: The path within the location to download the file.
        schema:
          type: string
    get:
      tags:
        - octoprint
      summary: Download a file.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: File not found.
        415:
          description: Unsupported Media Type.
  /api/files/preview/{target}/{filename}:
    parameters:
      - in: path
        name: target
        required: true
        description: The target project location.
        schema:
          type: string
          default: local
          enum:
            - local
            - sdcard
      - in: path
        name: filename
        required: true
        description: File name.
        schema:
          type: string
    get:
      summary: Download a preview image.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: File not found.
  /api/files:
    get:
      tags:
        - octoprint
      summary: Retrieve all files’ and folders’ information.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: If-None-Match
          description: ETag
          schema:
            type: string
          required: false
        - in: query
          name: recursive
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OctoAllFilesInfo"
          headers:
            ETag:
              schema:
                type: string
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/files/{target}:
    parameters:
      - in: path
        name: target
        required: true
        description: The target location to which to upload the file (local, sdcard).
        schema:
          type: string
          default: local
          enum:
            - local
            - sdcard
    get:
      tags:
        - octoprint
      summary: Retrieve all files’ and folders’ information for the target location.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: If-None-Match
          description: ETag
          schema:
            type: string
          required: false
        - in: query
          name: recursive
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OctoAllFilesInfo"
          headers:
            ETag:
              schema:
                type: string
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Not Found
    post:
      tags:
        - octoprint
      summary: Upload file or create folder.
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/OctoUploadFile"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/OctoCreateFolder"
      responses:
        201:
          description: No error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/OctoFileUploaded"
                  - $ref: "#/components/schemas/OctoFolderCreated"
        400:
          description: Could not create folder or file not found.
        403:
          $ref: "#/components/responses/Unauthorized"
        409:
          description: File already exist.
        415:
          description: Unsupported Media Type.
        500:
          description: File is too big.
  /api/files/{target}/{filename}:
    parameters:
      - in: path
        name: target
        required: true
        description: The target location to which to upload the file (local, sdcard).
        schema:
          type: string
          default: local
          enum:
            - local
            - sdcard
      - in: path
        name: filename
        required: true
        description: The path within the location to the file or folder.
        schema:
          type: string
    get:
      tags:
        - octoprint
      summary: Retrieve a specific file’s or folder’s information.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: If-None-Match
          description: ETag
          schema:
            type: string
          required: false
        - in: query
          name: recursive
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OctoFileOrFolderInfo"
          headers:
            ETag:
              schema:
                type: string
        304:
          description: Not Modified.
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Not Found
    post:
      tags:
        - octoprint
      summary: Issue a file command to an existing file.
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OctoFileCommand"
      responses:
        204:
          description: No error.
        400:
          description: Mandatory parameter is missing.
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Not Found.
        409:
          description: If the file is currently being printed.
        415:
          description: Unsupported Media Type.
        501:
          description: Unsupported command.
    delete:
      tags:
        - octoprint
      summary: Delete a file or folder.
      security:
        - ApiKeyAuth: []
      responses:
        204:
          description: No error
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: If location is neither local nor sdcard or the requested file was not found
        409:
          description: If the file to be deleted is currently being printed
  /api/telemetry:
    get:
      summary: Retrieve all printer telemetry.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TelemetryMini"
                  - $ref: "#/components/schemas/TelemetrySL1"
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/progress:
    get:
      summary: Retrieve all progress measure.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ProgressMini"
                  - $ref: "#/components/schemas/ProgressSL1"
        403:
          $ref: "#/components/responses/Unauthorized"
  /api/properties:
    get:
      summary: Retrieve a specific property information.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: values
          schema:
            type: array
            items:
              type: string
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Properties"
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Not Found
    post:
      summary: Set a property.
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Properties"
      responses:
        200:
          description: Ok.
        403:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Not Found.
  /api/job/material:
    get:
      summary: Feed the SL1 resin.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: value
          schema:
            enum: ["start", "continue", "back"]
      responses:
        200:
          description: OK
        403:
          $ref: "#/components/responses/Unauthorized"
        400:
          $ref: "#/components/responses/BadRequest"
  /api/project-name:
    get:
      summary: Retrieve all progress measure.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  project_name:
                    type: string
        403:
          $ref: "#/components/responses/Unauthorized"
components:
  schemas:
    OctoConnCurrent:
      type: object
      properties:
        baudrate:
          type: integer
          nullable: true
          example: null
        port:
          type: string
          nullable: true
          example: null
        printerProfile:
          type: string
          example: _default
        state:
          type: string
          example: Operational
    OctoConnOptions:
      type: object
      properties:
        baudratePreference:
          type: string
          nullable: true
          example: null
        baudrates:
          type: array
          items:
            type: integer
          example: []
        portPreference:
          type: string
          nullable: true
          example: null
        ports:
          type: array
          items:
            type: string
          example: []
        printerProfilePreference:
          type: string
          example: _default
        printerProfiles:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: _default
              name:
                type: string
                example: Prusa SL1
    OctoCommands:
      type: object
      properties:
        core:
          type: array
          default: []
          items:
            type: object
            nullable: true
        custom:
          type: array
          default: []
          items:
            type: object
            nullable: true
    OctoProfiles:
      type: object
      properties:
        _default:
          type: object
          properties:
            id:
              type: string
              example: _default
            name:
              type: string
              example: Prusa SL1
            model:
              type: string
              example: Original Prusa SL1
            color:
              type: string
              example: default
            current:
              type: boolean
              example: true
            default:
              type: boolean
              example: true
            heatedBed:
              type: boolean
              example: false
            heatedChamber:
              type: boolean
              example: false
            resource:
              type: string
              example: http://localhost/octoprint/api/printerprofiles/_default
    timestamp:
      type: number
      description: Unix Timestamep
    OctoTemperatureData:
      type: object
      properties:
        actual:
          type: number
          description: Current temperature
        target:
          type: number
          description: Target temperature
          nullable: true
        offset:
          type: number
          nullable: true
          description: Currenntly configured temperature offset to apply.
      example:
        actual: 22.5
        target: 50.0
        offset: 1.0
    OctoTemperatureState:
      type: object
      properties:
        tool0:
          $ref: "#/components/schemas/OctoTemperatureData"
        tool1:
          $ref: "#/components/schemas/OctoTemperatureData"
        tool2:
          $ref: "#/components/schemas/OctoTemperatureData"
        tool3:
          $ref: "#/components/schemas/OctoTemperatureData"
        bed:
          $ref: "#/components/schemas/OctoTemperatureData"
    OctoSDState:
      type: object
      properties:
        ready:
          type: boolean
          example: false
    OctoPrinterState:
      type: object
      properties:
        text:
          type: string
          example: Printing
        flags:
          type: object
          properties:
            operational:
              type: boolean
              example: false
            paused:
              type: boolean
              example: false
            printing:
              type: boolean
              example: true
            cancelling:
              type: boolean
              example: false
            pausing:
              type: boolean
              example: false
            sdReady:
              type: boolean
              example: false
            error:
              type: boolean
              example: false
            ready:
              type: boolean
              example: true
            closedOrError:
              type: boolean
              example: false
    OctoJob:
      type: object
      properties:
        file:
          type: object
          properties:
            name:
              type: string
              description: The name of the file without path.
              example: "harry_potter_hogwarts_anthony_mohimont.sl1"
              nullable: true
            origin:
              enum: ["local", "sdcard"]
              nullable: true
            path:
              type: string
              description: The path to the file within the location.
              example: "internal/harry_potter_hogwarts_anthony_mohimont.sl1"
              nullable: true
            date:
              type: integer
              description: Unix timestamp.
              example: 1574175255
              nullable: true
            size:
              type: integer
              description: The size of the file in bytes.
              example: 873151
              nullable: true
        estimatedPrintTime:
          type: number
          description: Estimated print time for the file in seconds.
          nullable: true
        lastPrintTime:
          type: integer
          description: Last print time for the file in seconds.
          nullable: true
        filament:
          type: object
          properties:
            length:
              type: number
              description: Length of filament used in mm.
              nullable: true
            volume:
              type: number
              description: Volume in filament used in cm3.
              nullable: true
          nullable: true
    OctoProgress:
      type: object
      properties:
        completion:
          type: number
          description: Percentage of completion of the current job.
          nullable: true
        filepos:
          type: integer
          nullable: true
        printTime:
          type: integer
          description: Time already spent printing in seconds.
          nullable: true
        printTimeLeft:
          type: integer
          description: Estimate of time left to print in seconds.
          nullable: true
    OctoUsers:
      type: object
      properties:
        active:
          type: boolean
          example: true
        admin:
          type: boolean
          example: true
        apikey:
          type: string
          nullable: true
        name:
          type: string
          example: prusa
        settings:
          type: object
          example: null
        user:
          type: boolean
          example: true
    OctoCommonFileInfo:
      type: object
      properties:
        origin:
          type: string
          example: local
        path:
          type: string
        display:
          type: string
        name:
          type: string
        size:
          type: integer
          example: 873151
        type:
          type: string
        typePath:
          type: array
          items:
            type: string
    OctoFileInfo:
      allOf:
        - $ref: "#/components/schemas/OctoCommonFileInfo"
        - type: object
      properties:
        refs:
          type: object
          properties:
            resource:
              type: string
            download:
              type: string
        gcodeAnalysis:
          type: object
          properties:
            estimatedPrintTime:
              type: number
            dimensions:
              type: object
              properties:
                height:
                  type: number
            material:
              type: string
              description: It is not compatible with latest OctoPrint.
        hash:
          type: string
        date:
          type: integer
          example: 1574156567
      example:
        origin: local
        path: internal/examples/harry_potter_hogwarts_a_mohimont.sl1
        display: harry_potter_hogwarts_a_mohimont.sl1
        name: harry_potter_hogwarts_a_mohimont.sl1
        size: 873151
        date: 1574156567
        type: machinecode
        typePath: [machinecode, gcode]
        hash: 5f972cc1cfb91f91f7c70d0dff6a0462a9de1d41
        refs:
          resource: http://localhost/octoprint/api/files/local/internal/examples/harry_potter_hogwarts_a_mohimont.sl1
          download: http://localhost/octoprint/api/downloads/local/internal/examples/harry_potter_hogwarts_a_mohimont.sl1
        gcodeAnalysis:
          estimatedPrintTime: 2445.0
          dimensions:
            height: 0.15
          material: Prusa Orange Tough 0.05
    OctoFolderInfo:
      allOf:
        - $ref: "#/components/schemas/OctoCommonFileInfo"
        - type: object
      properties:
        refs:
          type: object
          properties:
            resource:
              type: string
        children:
          type: array
          items:
            type: object
      example:
        origin: local
        path: internal/examples
        display: examples
        name: examples
        size: 873151
        type": folder
        typePath": [folder]
        refs:
          resource: http://localhost/octoprint/api/files/local/internal/examples
    OctoFullFolderInfo:
      allOf:
        - $ref: "#/components/schemas/OctoFolderInfo"
        - type: object
      properties:
        children:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/OctoFileInfo"
              - $ref: "#/components/schemas/OctoFolderInfo"
            discriminator:
              propertyName: type
    OctoFileOrFolderInfo:
      oneOf:
        - $ref: "#/components/schemas/OctoFileInfo"
        - $ref: "#/components/schemas/OctoFullFolderInfo"
    OctoAllFilesInfo:
      type: object
      properties:
        files:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/OctoFileInfo"
              - $ref: "#/components/schemas/OctoFullFolderInfo"
        free:
          type: integer
        total:
          type: integer
    OctoFileCommand:
      type: object
      properties:
        command:
          type: string
          example: select
        print:
          oneOf:
            - type: string
            - type: boolean
          example: true
    OctoCreateFolder:
      properties:
        path:
          type: string
          description: The path within the location to upload the file to or create the folder.
        foldername:
          type: string
          description: The name of the folder to create. Ignored when uploading a file.
      required:
        - path
        - foldername
    OctoUploadFile:
      properties:
        path:
          type: string
          description: The path within the location to upload the file to or create the folder.
        file:
          type: array
          items:
            type: string
            format: binary
          description: The file to upload, including a valid filename.
        select:
          type: string
          default: "true"
          description: Whether to select the file directly after upload (true) or not (false). Defaults to true.
      required:
        - path
        - file
    OctoFileUploaded:
      type: object
      properties:
        done:
          type: boolean
        files:
          type: object
          properties:
            local:
              type: object
              properties:
                name:
                  type: string
                  example: harry_potter_hogwarts_a_mohimont.sl1
                origin:
                  type: string
                  example: local
                path:
                  type: string
                  example: internal/examples/harry_potter_hogwarts_a_mohimont.sl1
                refs:
                  type: object
                  properties:
                    resource:
                      type: string
                      example: http://localhost/octoprint/api/files/local/internal/examples/harry_potter_hogwarts_a_mohimont.sl1
                    download:
                      type: string
                      example: http://localhost/octoprint/api/downloads/local/internal/examples/harry_potter_hogwarts_a_mohimont.sl1
    OctoFolderCreated:
      type: object
      properties:
        done:
          type: boolean
        folder:
          type: object
          properties:
            name:
              type: string
            origin:
              type: string
            path:
              type: string
            refs:
              type: object
              properties:
                resource:
                  type: string
    Properties:
      type: object
      properties:
        exposure_time_ms:
          type: number
        exposure_time_first_ms:
          type: number
    TelemetryMini:
      type: object
      properties:
        temp_bed:
          type: number
        temp_nozzle:
          type: number
        material:
          type: string
    TelemetrySL1:
      type: object
      properties:
        blower_fan:
          type: integer
        cover_closed:
          type: boolean
        temp_amb:
          type: number
        temp_cpu:
          type: number
        temp_led:
          type: number
        uv_led_fan:
          type: integer
        rear_fan:
          type: integer
    ProgressMini:
      type: object
      properties:
        progress:
          type: number
        pos_z_mm:
          type: number
        printing_speed:
          type: number
        flow_factor:
          type: number
        print_dur:
          type: string
        time_est:
          type: string
        filament_status:
          type: string
    ProgressSL1:
      type: object
      properties:
        total_layers:
          type: integer
        current_layer:
          type: integer
        remaining_material:
          type: number
        consumed_material:
          type: number
        progress:
          type: number
        time_elapsed:
          type: number
        remaining_time:
          type: number
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  responses:
    Unauthorized:
      description: Unauthorized
    NotModified:
      description: Not Modified
    BadRequest:
      description: Bad Request
    NotFound:
      description: Not Found
    Conflict:
      description: Conflict
    UnsupportedMediaType:
      description: Unsupported Media Type
    InternalServerError:
      description: Internal Server Error
    NotImplemented:
      description: Not Implemented
